for a in \
Aseg1-prot1A.fasta \
Aseg1-prot1B.fasta \
Aseg2-prot1A.fasta \
Aseg2-prot1B.fasta \
Aseg2-prot2A.fasta \
Aseg2-prot2B.fasta \
Aseg2-prot2C.fasta \
Aseg2-prot2D.fasta \
Aseg2-prot2E.fasta \
Aseg2-prot2F.fasta \
Aseg2-prot2G.fasta \
Aseg2-prot2H.fasta \
Aseg2-prot2I.fasta \
Aseg2-prot2J.fasta \
Aseg2-prot2K.fasta \
Aseg2-prot2L.fasta \
Aseg2-prot2M.fasta \
Aseg3-prot1A.fasta \
Aseg3-prot2A.fasta \
Aseg3-prot2B.fasta \
Aseg3-prot2C.fasta \
Aseg3-prot2D.fasta \
Aseg4-prot3A.fasta \
Aseg4-prot5A.fasta \
Aseg4-prot5B.fasta \
Aseg4-prot7A.fasta \
Aseg4-prot7C.fasta \
Aseg4-prot7D.fasta \
Aseg4-prot7E.fasta \
Aseg4-prot7F.fasta \
Aseg4-protA.fasta \
Aseg4-protB.fasta \
Aseg4-protC.fasta \
Aseg4-protD.fasta \
Aseg4-protE.fasta \
Aseg4-protF.fasta \
Aseg4-protG.fasta \
Aseg4-protH.fasta \
Aseg4-protI.fasta \
Aseg4-protJ.fasta \
Aseg4-protK.fasta \
Aseg4-protL.fasta \
Aseg4-protM.fasta \
Aseg4-protN.fasta \
Aseg4-protO.fasta \
Aseg4-protP.fasta \
Aseg5-prot1A.fasta \
Aseg6-prot1A.fasta \
Aseg6-prot1B.fasta \
Aseg6-prot1C.fasta \
Aseg6-prot1D.fasta \
Aseg6-prot1E.fasta \
Aseg6-prot1F.fasta \
Aseg6-prot1G.fasta \
Aseg7-prot1A.fasta \
Aseg7-prot2A.fasta \
Aseg7-prot2B.fasta \
Aseg8-prot1A.fasta \
Aseg8-prot1B.fasta \
Aseg8-prot1C.fasta \
Aseg8-prot1D.fasta \
Aseg8-prot1E.fasta \
Aseg8-prot1F.fasta \
Aseg8-prot1G.fasta \
Aseg8-prot1I.fasta \
Aseg8-prot1J.fasta \
Aseg8-prot1K.fasta \
Aseg8-prot2A.fasta \
Bseg1-prot1A.fasta \
Bseg2-prot1A.fasta \
Bseg3-prot1A.fasta \
Bseg4-prot1A.fasta \
Bseg4-prot1B.fasta \
Bseg4-prot1C.fasta \
Bseg5-prot1A.fasta \
Bseg6-prot1A.fasta \
Bseg6-prot2A.fasta \
Bseg6-prot2B.fasta \
Bseg7-prot1A.fasta \
Bseg7-prot2A.fasta \
Bseg7-prot2B.fasta \
Bseg7-prot2C.fasta \
Bseg8-prot1A.fasta \
Bseg8-prot1B.fasta \
Bseg8-prot1C.fasta \
Bseg8-prot2A.fasta \
Bseg8-prot2B.fasta \
Cseg1-prot1A.fasta \
Cseg2-prot1A.fasta \
Cseg3-prot1A.fasta \
Cseg4-prot1A.fasta \
Cseg5-prot1A.fasta \
Cseg6-prot1A.fasta \
Cseg6-prot2A.fasta \
Cseg7-prot1A.fasta \
Cseg7-prot2A.fasta \
; do
    perl rename-fasta.pl $a > renamed.$a
done
