for a in \
Aseg4-mature3A1.fasta \
Aseg4-mature3A2.fasta \
Aseg4-mature3A3.fasta \
Aseg4-mature5A1.fasta \
Aseg4-mature5A2.fasta \
Aseg4-mature5A3.fasta \
Aseg4-mature5B1.fasta \
Aseg4-mature5B2.fasta \
Aseg4-mature5B3.fasta \
Aseg4-mature7A1.fasta \
Aseg4-mature7A2.fasta \
Aseg4-mature7A3.fasta \
Aseg4-mature7C1.fasta \
Aseg4-mature7C2.fasta \
Aseg4-mature7C3.fasta \
Aseg4-mature7D1.fasta \
Aseg4-mature7D2.fasta \
Aseg4-mature7D3.fasta \
Aseg4-mature7E1.fasta \
Aseg4-mature7E2.fasta \
Aseg4-mature7E3.fasta \
Aseg4-mature7F1.fasta \
Aseg4-mature7F2.fasta \
Aseg4-mature7F3.fasta \
Aseg4-matureA1.fasta \
Aseg4-matureA2.fasta \
Aseg4-matureA3.fasta \
Aseg4-matureB1.fasta \
Aseg4-matureB2.fasta \
Aseg4-matureB3.fasta \
Aseg4-matureC1.fasta \
Aseg4-matureC2.fasta \
Aseg4-matureC3.fasta \
Aseg4-matureD1.fasta \
Aseg4-matureD2.fasta \
Aseg4-matureD3.fasta \
Aseg4-matureE1.fasta \
Aseg4-matureE2.fasta \
Aseg4-matureE3.fasta \
Aseg4-matureF1.fasta \
Aseg4-matureF2.fasta \
Aseg4-matureF3.fasta \
Aseg4-matureG1.fasta \
Aseg4-matureG2.fasta \
Aseg4-matureG3.fasta \
Aseg4-matureH1.fasta \
Aseg4-matureH2.fasta \
Aseg4-matureH3.fasta \
Aseg4-matureI1.fasta \
Aseg4-matureI2.fasta \
Aseg4-matureI3.fasta \
Aseg4-matureJ1.fasta \
Aseg4-matureJ2.fasta \
Aseg4-matureJ3.fasta \
Aseg4-matureK1.fasta \
Aseg4-matureK2.fasta \
Aseg4-matureK3.fasta \
Aseg4-matureL1.fasta \
Aseg4-matureL2.fasta \
Aseg4-matureL3.fasta \
Aseg4-matureM1.fasta \
Aseg4-matureM2.fasta \
Aseg4-matureM3.fasta \
Aseg4-matureN1.fasta \
Aseg4-matureN2.fasta \
Aseg4-matureN3.fasta \
Aseg4-matureO1.fasta \
Aseg4-matureO2.fasta \
Aseg4-matureO3.fasta \
Aseg4-matureP1.fasta \
Aseg4-matureP2.fasta \
Aseg4-matureP3.fasta \
; do
    perl rename-fasta.pl $a > renamed.$a
done
