# B seg 1
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg1/prot1A.fasta -O Bseg1-prot1A.fasta
# B seg 2
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg2/prot1A.fasta -O Bseg2-prot1A.fasta
# B seg 3
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg3/prot1A.fasta -O Bseg3-prot1A.fasta
# B seg 4
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg4/prot1A.fasta -O Bseg4-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg4/prot1B.fasta -O Bseg4-prot1B.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg4/prot1C.fasta -O Bseg4-prot1C.fasta
# B seg 5
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg5/prot1A.fasta -O Bseg5-prot1A.fasta
# B seg 6
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg6/prot1A.fasta -O Bseg6-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg6/prot2A.fasta -O Bseg6-prot2A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg6/prot2B.fasta -O Bseg6-prot2B.fasta
# B seg 7
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg7/prot1A.fasta -O Bseg7-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg7/prot2A.fasta -O Bseg7-prot2A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg7/prot2B.fasta -O Bseg7-prot2B.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg7/prot2C.fasta -O Bseg7-prot2C.fasta
# B seg 8
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg8/prot1A.fasta -O Bseg8-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg8/prot1B.fasta -O Bseg8-prot1B.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg8/prot1C.fasta -O Bseg8-prot1C.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg8/prot2A.fasta -O Bseg8-prot2A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-B/Seg8/prot2B.fasta -O Bseg8-prot2B.fasta
