# C seg 1
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg1/prot1A.fasta -O Cseg1-prot1A.fasta
# C seg 2
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg2/prot1A.fasta -O Cseg2-prot1A.fasta
# C seg 3
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg3/prot1A.fasta -O Cseg3-prot1A.fasta
# C seg 4
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg4/prot1A.fasta -O Cseg4-prot1A.fasta
# C seg 5
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg5/prot1A.fasta -O Cseg5-prot1A.fasta
# C seg 6
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg6/prot1A.fasta -O Cseg6-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg6/prot2A.fasta -O Cseg6-prot2A.fasta
# C seg 7
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg7/prot1A.fasta -O Cseg7-prot1A.fasta
wget https://ftp.ncbi.nih.gov/genomes/INFLUENZA/ANNOTATION/PROTEIN-C/Seg7/prot2A.fasta -O Cseg7-prot2A.fasta
